# Generated by Django 2.2.6 on 2020-03-04 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_auto_20200228_1747'),
        ('profiles', '0006_auto_20200304_0057'),
    ]

    operations = [
    ]
