# Generated by Django 2.2.5 on 2020-03-04 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_auto_20200304_1539'),
        ('profiles', '0008_auto_20200304_1414'),
    ]

    operations = [
    ]
