# Generated by Django 2.2.5 on 2020-03-05 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0011_auto_20200305_1608'),
        ('profiles', '0011_auto_20200304_2202'),
    ]

    operations = [
    ]
