# Generated by Django 2.2.6 on 2020-03-05 00:47

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('profiles', '0012_mate'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Mate',
            new_name='Mates',
        ),
    ]
