# Generated by Django 2.2.6 on 2020-04-22 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0017_auto_20200415_1526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='education',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='workplace',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
    ]
