# Generated by Django 3.0.4 on 2020-04-22 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0017_auto_20200415_1526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='status',
            field=models.CharField(choices=[('Married', 'Married'), ('Single', 'Single'), ('Its Complicated', 'Its Complicated'), ('Engaged', 'Engaged'), ('Dating', 'Dating'), ('In a relationship', 'In a relationship')], default=1, max_length=17),
        ),
    ]
