# Generated by Django 3.0.2 on 2020-04-20 14:08

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0018_auto_20200420_1501'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='dob',
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other'), ('Rather Not Say', 'Rather Not Say')], default=1, max_length=14),
        ),
        migrations.AlterField(
            model_name='profile',
            name='location',
            field=django_countries.fields.CountryField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='status',
            field=models.CharField(blank=True, choices=[('Married', 'Married'), ('Single', 'Single'), ('Its Complicated', 'Its Complicated'), ('Engaged', 'Engaged'), ('Dating', 'Dating'), ('In a relationship', 'In a relationship')], default=1, max_length=17),
        ),
    ]
