# Generated by Django 3.0.2 on 2020-04-22 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0019_auto_20200420_1508'),
        ('profiles', '0018_auto_20200422_1231'),
    ]

    operations = [
    ]
