# Generated by Django 2.2.6 on 2020-04-22 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0019_auto_20200420_1508'),
        ('profiles', '0018_auto_20200422_1246'),
        ('profiles', '0018_auto_20200422_1231'),
    ]

    operations = [
    ]
