# Generated by Django 3.0.2 on 2020-04-22 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0021_auto_20200422_1338'),
        ('profiles', '0018_auto_20200422_1246'),
    ]

    operations = [
    ]
