# Generated by Django 3.0.2 on 2020-04-24 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0023_profile_dob'),
        ('profiles', '0021_auto_20200422_1331'),
    ]

    operations = [
    ]
