# Generated by Django 2.2.6 on 2020-04-23 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0021_auto_20200422_1331'),
        ('profiles', '0023_profile_dob'),
    ]

    operations = [
    ]
