# Generated by Django 3.0.2 on 2020-04-25 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0024_merge_20200423_2112'),
        ('profiles', '0024_merge_20200424_2149'),
    ]

    operations = [
    ]
