# Generated by Django 2.2.5 on 2020-02-26 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_post_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='body',
            new_name='description',
        ),
    ]
