# Generated by Django 2.2.6 on 2020-03-04 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_auto_20200226_1042'),
        ('post', '0005_remove_post_created_at'),
    ]

    operations = [
    ]
