# Generated by Django 3.0.2 on 2020-04-04 00:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0009_auto_20200403_2128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(default=66, on_delete=django.db.models.deletion.CASCADE, to='post.Post'),
        ),
    ]
