# Generated by Django 3.0.2 on 2020-04-11 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0011_auto_20200411_1614'),
    ]

    operations = [
        migrations.AddField(
            model_name='postfile',
            name='test',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
