# Generated by Django 3.0.2 on 2020-04-12 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0012_postfile_test'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postfile',
            name='test',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
