# Generated by Django 3.0.2 on 2020-04-12 21:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('post', '0013_auto_20200412_2220'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postfile',
            name='test',
        ),
        migrations.AddField(
            model_name='postfile',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
