# Generated by Django 3.0.2 on 2020-04-12 23:53

from django.db import migrations, models
import post.models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0014_auto_20200412_2221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postfile',
            name='files',
            field=models.FileField(blank=True, null=True, upload_to=post.models.PostFile.upload_path),
        ),
    ]
