# Generated by Django 3.0.4 on 2020-04-20 17:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('post', '0017_auto_20200415_1503'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_reason', models.CharField(choices=[('Language', 'Language'), ('Violence', 'Violence'), ('Spam', 'Spam'), ('Harassment', 'Harassment'), ('Terrorism', 'Terrorism'), ('Hate Speech', 'Hate Speech'), ('Unauthorized Sales', 'Unauthorized Sales')], default=1, max_length=18)),
                ('report', models.CharField(max_length=500, null=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post.Post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
