# Generated by Django 3.0.4 on 2020-04-21 15:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0018_report'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='user',
        ),
        migrations.AlterField(
            model_name='report',
            name='post',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='post.Post'),
        ),
        migrations.AlterField(
            model_name='report',
            name='report',
            field=models.CharField(choices=[('Language', 'Language'), ('Violence', 'Violence'), ('Spam', 'Spam'), ('Harassment', 'Harassment'), ('Terrorism', 'Terrorism'), ('Hate Speech', 'Hate Speech'), ('Unauthorized Sales', 'Unauthorized Sales')], default=1, max_length=18),
        ),
        migrations.AlterField(
            model_name='report',
            name='report_reason',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
