# Generated by Django 2.2.6 on 2020-04-18 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('likes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='like',
            name='state',
            field=models.BooleanField(null=True),
        ),
    ]
