# Generated by Django 3.0.2 on 2020-03-09 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('likes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='like',
            old_name='owner',
            new_name='user',
        ),
    ]
