# Generated by Django 3.0.2 on 2020-04-15 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('likes', '0002_auto_20200309_1923'),
    ]

    operations = [
        migrations.AddField(
            model_name='like',
            name='state',
            field=models.BooleanField(null=True),
        ),
    ]
