# Generated by Django 3.0.2 on 2020-04-25 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('likes', '0003_auto_20200424_2154'),
        ('likes', '0003_auto_20200425_0200'),
    ]

    operations = [
    ]
