# Generated by Django 3.0.2 on 2020-03-25 18:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20200325_1208'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductDetailImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detail_image', models.ImageField(blank=True, upload_to='product_images/')),
                ('product', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='detail_images', to='shop.Product')),
            ],
        ),
    ]
