# Generated by Django 3.0.2 on 2020-03-28 16:31

from django.db import migrations, models
import shop.models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_productdetailimages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdetailimages',
            name='detail_image',
            field=models.ImageField(blank=True, upload_to=shop.models.ProductDetailImages.upload_path),
        ),
    ]
