# Generated by Django 3.0.2 on 2020-03-29 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20200328_1631'),
        ('shop', '0002_auto_20200325_1156'),
    ]

    operations = [
    ]
