# Generated by Django 3.0.2 on 2020-03-30 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20200325_1211'),
        ('shop', '0005_merge_20200329_2136'),
    ]

    operations = [
    ]
