# Generated by Django 3.0.2 on 2020-03-28 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='gender_choice',
            field=models.CharField(max_length=1, null=True),
        ),
    ]
