# Generated by Django 3.0.2 on 2020-03-28 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_cartitem_gender_choice'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='gender_choice',
            new_name='gender',
        ),
    ]
