# Generated by Django 3.0.2 on 2020-04-24 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='is_superuser',
        ),
        migrations.AddField(
            model_name='customuser',
            name='superuser',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='test',
            field=models.DateField(blank=True, null=True),
        ),
    ]
