# Generated by Django 3.0.4 on 2020-04-22 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_remove_customuser_is_superuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='superuser',
            field=models.BooleanField(default=False),
        ),
    ]
