# Generated by Django 2.2.6 on 2020-04-23 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_remove_customuser_is_superuser'),
        ('user', '0003_auto_20200422_1339'),
    ]

    operations = [
    ]
