# Generated by Django 2.2.5 on 2020-02-26 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20200225_1721'),
        ('user', '0006_auto_20200226_0032'),
    ]

    operations = [
    ]
