# Generated by Django 2.2.6 on 2020-02-27 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_merge_20200226_1253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='password',
            field=models.CharField(blank=True, max_length=90, null=True),
        ),
    ]
