# Generated by Django 2.2.6 on 2020-03-04 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_auto_20200228_1747'),
        ('user', '0008_auto_20200227_0018'),
    ]

    operations = [
    ]
