# Generated by Django 2.2.5 on 2020-03-04 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_merge_20200304_1256'),
        ('user', '0008_auto_20200228_2014'),
    ]

    operations = [
    ]
