# Generated by Django 3.0.2 on 2020-03-29 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('private_messages', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='recipient',
            new_name='recipien',
        ),
    ]
