# Generated by Django 3.0.2 on 2020-03-29 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('private_messages', '0002_auto_20200329_2225'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='recipien',
            new_name='recipient',
        ),
    ]
